name: Frontend CI

on:
  push:
    branches: [ frontend ]
  pull_request:
    branches: [ main, frontend, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      # - name: Lint
      #   run: |
      #     cd frontend
      #     npm run lint

      # - name: Run tests
      #   run: |
      #     cd frontend
      #     npm run test

      - name: Build
        run: |
          cd frontend
          npm run build || true
